### ISSUE TITLE
Deprecate repo and npm package

### ISSUE THREAD

**Issue by bekos** [AnBauer/ngx-lightning#4]
Hi @AnBauer :)

 There are already new releases on the original repo (https://github.com/ng-lightning/ng-lightning) that solve the issues for which this fork was created, plus new many components, new features, better infrastructure etc. Although I understand and I would like to thank you, i suggest that you deprecate this repo and npm package, so people will not be confused in the future as what is the best option to use.

**Comment by AnBauer** [comment]
Fair enough :) 
I will deprecate the package and try to switch back to ng-lightning with the customer project. Looking forward to the new features - your new Doc-Page looks great!
